/**
 * Export API Routes
 * ==================
 * Export project files as ZIP
 */

const express = require('express');
const router = express.Router();
const db = require('../config/database');
const JSZip = require('jszip');

// GET /api/projects/:projectId/export - Export project as ZIP
router.get('/:projectId/export', async (req, res) => {
    try {
        const { projectId } = req.params;

        // Get project
        const isNumeric = /^\d+$/.test(projectId);
        const whereClause = isNumeric ? 'id = ?' : 'project_uid = ?';
        const project = await db.queryOne(`SELECT * FROM projects WHERE ${whereClause}`, [projectId]);

        if (!project) {
            return res.status(404).json({ success: false, error: 'Project not found' });
        }

        // Get project files
        const files = await db.query(`
            SELECT filename, content
            FROM project_files
            WHERE project_id = ?
        `, [project.id]);

        if (files.length === 0) {
            return res.status(400).json({ success: false, error: 'No files to export' });
        }

        // Create ZIP
        const zip = new JSZip();

        // Add all project files
        files.forEach(file => {
            zip.file(file.filename, file.content || '');
        });

        // Add README
        const readme = `# ${project.name}

Generated by Codeকথা AI Website Builder

## Project Info
- Theme: ${project.theme || 'N/A'}
- Color Theme: ${project.color_theme || 'N/A'}
- Created: ${project.created_at}
- Last Updated: ${project.updated_at}

## Files
${files.map(f => `- ${f.filename}`).join('\n')}

## Usage
Simply open index.html in your browser.

## Customization
Edit the HTML, CSS, and JavaScript files to customize your website.
`;
        zip.file('README.md', readme);

        // Generate ZIP buffer
        const zipBuffer = await zip.generateAsync({
            type: 'nodebuffer',
            compression: 'DEFLATE',
            compressionOptions: { level: 9 }
        });

        // Set headers for download
        const filename = `${project.name.toLowerCase().replace(/\s+/g, '-')}.zip`;
        res.set({
            'Content-Type': 'application/zip',
            'Content-Disposition': `attachment; filename="${filename}"`,
            'Content-Length': zipBuffer.length
        });

        res.send(zipBuffer);

    } catch (error) {
        console.error('Error exporting project:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

// POST /api/export/files - Export arbitrary files as ZIP (for editor)
router.post('/files', async (req, res) => {
    try {
        const { files, projectName } = req.body;

        if (!files || typeof files !== 'object' || Object.keys(files).length === 0) {
            return res.status(400).json({ success: false, error: 'No files to export' });
        }

        // Create ZIP
        const zip = new JSZip();

        // Add all files
        for (const [filename, content] of Object.entries(files)) {
            zip.file(filename, content || '');
        }

        // Add README
        const readme = `# ${projectName || 'My Project'}

Generated by Codeকথা AI Website Builder

## Files
${Object.keys(files).map(f => `- ${f}`).join('\n')}

## Usage
Simply open index.html in your browser.
`;
        zip.file('README.md', readme);

        // Generate ZIP buffer
        const zipBuffer = await zip.generateAsync({
            type: 'nodebuffer',
            compression: 'DEFLATE',
            compressionOptions: { level: 9 }
        });

        // Set headers for download
        const filename = `${(projectName || 'project').toLowerCase().replace(/\s+/g, '-')}.zip`;
        res.set({
            'Content-Type': 'application/zip',
            'Content-Disposition': `attachment; filename="${filename}"`,
            'Content-Length': zipBuffer.length
        });

        res.send(zipBuffer);

    } catch (error) {
        console.error('Error exporting files:', error);
        res.status(500).json({ success: false, error: error.message });
    }
});

module.exports = router;
